# Generated by Django 5.2.1 on 2025-05-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="BlogPost",
        ),
    ]
