# Generated by Django 5.2.1 on 2025-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_posts", "0002_rename_post_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Business & Finance", "Business & Finance"),
                    ("Health & Wellness", "Health & Wellness"),
                    ("Entertainment", "Entertainment"),
                    ("Lifestyle", "Lifestyle"),
                    ("Education", "Education"),
                    ("Sports", "Sports"),
                    ("Politics & Current Affairs", "Politics & Current Affairs"),
                    ("Science", "Science"),
                    ("Food & Cooking", "Food & Cooking"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
