# Generated by Django 5.2.1 on 2025-05-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_posts", "0003_blogpost_category_blogpost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
